CREATE TABLE properties (
    id                   UUID           PRIMARY KEY DEFAULT uuid_generate_v4(),
    host_id              UUID           NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title                VARCHAR(255)   NOT NULL,
    description          TEXT,
    property_type        VARCHAR(100)   NOT NULL,
    city                 VARCHAR(100)   NOT NULL,
    country              VARCHAR(100)   NOT NULL,
    address              TEXT           NOT NULL,
    latitude             DECIMAL(9, 6),
    longitude            DECIMAL(9, 6),
    price_per_night      INTEGER        NOT NULL CHECK (price_per_night > 0),
    bedrooms             INTEGER        NOT NULL DEFAULT 1 CHECK (bedrooms >= 0),
    bathrooms            INTEGER        NOT NULL DEFAULT 1 CHECK (bathrooms >= 0),
    max_guests           INTEGER        NOT NULL DEFAULT 1 CHECK (max_guests > 0),
    amenities            TEXT,
    min_nights           INTEGER        NOT NULL DEFAULT 1 CHECK (min_nights > 0),
    available            BOOLEAN        NOT NULL DEFAULT TRUE,
    rating               DECIMAL(3, 2)  CHECK (rating >= 0 AND rating <= 5),
    review_count         INTEGER        NOT NULL DEFAULT 0,
    cloudinary_public_id VARCHAR(255),
    thumbnail_url        TEXT,
    created_at           TIMESTAMP      NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP      NOT NULL DEFAULT NOW()
);